doctrine:
    dbal:
        dbname: database
        host: localhost
        port: 1234
        user: root
        password:
        driver: pdo_mysql
        # if the url option is specified, it will override the above config
        url: mysql://root:@127.0.0.1:3306/db_name
        # the DBAL driverClass option
        driver_class: App\DBAL\MyDatabaseDriver
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
